site_name: å€‹é«”ç¶“æ¿Ÿå­¸
site_dir: site
repo_url: https://github.com/yueswater/microecon_ta
repo_name: yueswater/microecon_ta

nav:
  - ç¬¬ 0 ç«  &nbsp; å€‹é«”ç¶“æ¿Ÿå­¸æ•¸å­¸åŸºç¤: 
    - ch0/index.md
    - 0.1 &nbsp; å‡½æ•¸: ch0/function.md
    - 0.2 &nbsp; æ¥µé™èˆ‡é€£çºŒæ€§: ch0/limit.md
    - 0.3 &nbsp; å¾®åˆ†: ch0/diff.md
    - 0.4 &nbsp; ç©åˆ†: ch0/integration.md
    - 0.5 &nbsp; åå¾®åˆ†: ch0/partial_diff.md
    - 0.6 &nbsp; å…¨å¾®åˆ†: ch0/total_diff.md
    - 0.7 &nbsp; æ³°å‹’ç´šæ•¸èˆ‡æ³°å‹’å±•é–‹: ch0/taylor.md
    - 0.8 &nbsp; è¯ç«‹æ–¹ç¨‹å¼çš„æ±‚è§£: ch0/simul_eqs.md
    - 0.9 &nbsp; æœ€é©åŒ–: ch0/optimization.md
    - 0.10 &nbsp; ç¾å€¼èˆ‡æœªä¾†å€¼: ch0/pv_fv.md
  - ç¬¬ 1 ç«  &nbsp; éœ€æ±‚èˆ‡ä¾›çµ¦: 
    - ch1/index.md
    - 1.1 &nbsp; éœ€æ±‚: ch1/demand.md
    - 1.2 &nbsp; ä¾›çµ¦: ch1/supply.md
    - 1.3 &nbsp; å‡è¡¡åˆ†æ: ch1/market.md
  - ç¬¬ 2 ç«  &nbsp; å½ˆæ€§: 
    - ch2/index.md
    - 2.1 &nbsp; åƒ¹æ ¼å½ˆæ€§: ch2/price_elasticity.md
    - 2.2 &nbsp; äº¤å‰å½ˆæ€§èˆ‡æ‰€å¾—å½ˆæ€§: ch2/cross_and_income_elasticity.md
    - 2.3 &nbsp; å½ˆæ€§æ‡‰ç”¨: ch2/elasticity_application.md
  - ç¬¬ 3 ç«  &nbsp; ä¾›éœ€æ¨¡å‹æ‡‰ç”¨: 
    - ch3/index.md
    - 3.1 &nbsp; é™åƒ¹æ”¿ç­–: ch3/price_control.md
    - 3.2 &nbsp; é™é‡æ”¿ç­–: ch3/quantity_control.md
    - 3.3 &nbsp; èª²ç¨…æ”¿ç­–: ch3/tax.md
    - 3.4 &nbsp; è£œè²¼æ”¿ç­–: ch3/subsidy.md
  - ç¬¬ 4 ç«  &nbsp; æ¶ˆè²»è€…ç†è«–: 
    - ch4/index.md
    - 4.1 &nbsp; æ•ˆç”¨: ch4/utility.md
    - 4.2 &nbsp; é ç®—é™åˆ¶å¼: ch4/budget_constraint.md
    - 4.3 &nbsp; æ¶ˆè²»è€…æœ€é©é¸æ“‡: ch4/optimal_choice.md
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: white
      accent: light blue
      toggle:
          icon: material/weather-night
          name: åˆ‡æ›æ·±è‰²æ¨¡å¼
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ›æ·ºè‰²æ¨¡å¼
  font:
    text: Noto Sans TC
    code: Fira Code
  features:
    - announce
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.footnote.tooltips
  icon:
    repo: fontawesome/brands/github
extra:
  alternate:
    - name: ç¹é«”ä¸­æ–‡
      link: /
      lang: zh-Hant
    - name: English
      link: /en/
      lang: en
  announce:
    dismiss: true
    text: >
      ğŸ“¢ æœ¬èª²ç¨‹çš„åŠ©æ•™èª²æ™‚é–“å°‡æ–¼ä¹æœˆåˆå…¬å¸ƒï¼Œè«‹åŒå­¸éš¨æ™‚æ³¨æ„ç¶²ç«™æ›´æ–°ã€‚
  hyvor_talk:
    website_id: "13970"
extra_javascript:
  - js/quiz.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - styles.css
  - stylesheets/extra.css
markdown_extensions:
  - footnotes
  - admonition
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
plugins:
  - caption:
      figure:
        caption_prefix: "åœ– {index}ï¼š"
  - glightbox
  - search:
      enabled: true
      lang: zh
